[build]
  publish = "."      # Veröffentliche das aktuelle Verzeichnis

# Regel: Leite alles, was NICHT existiert, auf die App um.
# WICHTIG: Kein 'force = true' hier!
# Das sorgt dafür, dass 'links.json' automatisch geladen wird, weil es existiert.
[[redirects]]
  from = "/go/*"
  to = "/go/index.html"
  status = 200
